### ISSUE TITLE
Bar chart and aspect ratio

### ISSUE THREAD

**Issue by jbwl** [fullscale/dangle#2]
Hi, thank you for creating dangle, I am thrilled by its ease of use. Hopefully it is not a dead project?

My question is about the horizontal bar chart like in your example at http://www.fullscale.co/dangle/demo/

I use it to display a term_stats facet, and the number of facet entries is variable. I would like to keep each bar at a fixed height and the font at a fixed size rather than automatically adapting the bar height and font size to the number of returned facets, making them either too small if there are a lot of members in the facet, or extremely high if there is for example only one member. This doesn't look too professional.

I would like the container of the bars to stretch down the page to accommodate for any number of fixed height bars.

If this is a D3 question, please let me know.

Thank you

**Comment by egaumer** [comment]
This is something we can look in to. The issue is that the SVG container needs to have an initial aspect ratio (size) which means we'd need to know the max number of items that can be displayed. Once the container ratio is set, it can't be changed (at least not as far as I can see without reloading the page).

It also means that if we initially display 20 entries and then apply a filter which reduces that to 5 items, the container will still be large enough to handle 20 (i.e., you'll end up with a lot of extra whitespace). Could also get wonky with regards to scaling on mobile devices etc.

I do agree there should be a better way to handle this.

**Comment by jbwl** [comment]
Thank you for the explanation. I think due to the way an SVG container works, it might be out of the scope of dangle to work around this limitation.

As for vertical bar charts, my use case is so simple that I am happy with D3's HTML output as demonstrated here:  http://mbostock.github.io/d3/tutorial/bar-1.html
HTML containers offer exactly what I need in terms of expanding and shrinking gracefully. 

It would be great if dangle would incorporate D3's HTML output as well.
